GET http://localhost:3000/checkout

###
GET http://localhost:3000/checkout/

###
POST http://localhost:3000/checkout
Content-Type: application/json

{
    "checkAmout": ,
    "itemId": "",
    "userId": "",
    "shopId": ""
}

###
PUT  http://localhost:3000/checkout/
Content-Type: application/json

{
    "categoryName": "Fashion"
}

###
DELETE http://localhost:3000/checkout/
