GET http://192.168.159.1:3000/user

###
GET http://localhost:3000/user/40f9bdc6-e90e-44f9-ae2d-f72d2020ce8a

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "userName": "Ahmad",
    "password": "12345"
}

###
PUT  http://localhost:3000/user/40f9bdc6-e90e-44f9-ae2d-f72d2020ce8a
Content-Type: application/json

{
    "userName": "Muhaha",
    "password": "12345"
}

###
DELETE http://localhost:3000/user/40f9bdc6-e90e-44f9-ae2d-f72d2020ce8a
